### ISSUE TITLE
make a kazuma kiryu facecam typing plugin 

### ISSUE THREAD

**Issue by ErronZak** [revenge-mod/Revenge#10]
a plugin that adds a facecam of kazuma kiryu in the top left or top right of your screen basically whenever you are typing kazuma moves his hands when you send the message kazuma nods, to understand what I mean refer to this gif of kazuma kiryu typing "BOOOOBS" or the second gif https://cdn.discordapp.com/attachments/809232676590059550/1190008938696032317/RDT_20231228_1746551194849672011862037.gif?ex=65a03d30&is=658dc830&hm=653392a2b7bb897df0bbc8ca91381402980f6c22d1a7eb8b30192f77c2c03434& 

https://cdn.discordapp.com/attachments/1205207690352005243/1208913839257686097/yXOy4hYw.gif?ex=65e503bf&is=65d28ebf&hm=62ce39acb04a42e69baa25f367083692285d01680caf72ac6df88f1c1ba92ec9&

bonus : you can add this song to be playing when the plugin is active (song can be turned off) : https://youtu.be/eO2J-pwpU8Y

**Comment by nexpid** [comment]
@ErronZak could you send the first gif again pretty please the link broke
