### ISSUE TITLE
Discord Server

### ISSUE THREAD

**Issue by OrangeZXZ** [revenge-mod/Revenge#11]
I think Revenge should have an Discord Server for Plugins, Themes, etc and also for releases notifications until there will be an fork for Vendetta Manager

**Comment by PalmDevs** [comment]
It already exists, [check the Links section](https://github.com/revenge-mod)

**Comment by KaKi87** [comment]
Hi,
I'm getting "invites paused".
Any idea when shound try again ?
Thanks

**Comment by OrangeZXZ** [comment]
> Hi,
> I'm getting "invites paused".
> Any idea when should try again ?
> Thanks

I just created this link could you try it?
https://discord.com/invite/epRGvApm7G

**Comment by KaKi87** [comment]
I'm still getting this :

![](https://github.com/revenge-mod/Revenge/assets/21284089/ac153b62-d2cc-407c-9812-8a4c5713124d)

It seems to be a server-wide admin-level setting.

**Comment by PalmDevs** [comment]
Hey there, the invite links are now unpaused. We were experiencing join raids.

**Comment by KaKi87** [comment]
I understand, I joined now, thanks.
