### ISSUE TITLE
[Feature] Translations

### ISSUE THREAD

**Issue by speedlorenzo12** [revenge-mod/Revenge#12]
I would suggest implementing an automatic translator like the creator of Cloud Sync but  in the client

**Comment by riivx** [comment]
can you please elaborate on what you meant?
automatic translator plugin or translation in mod's menus?

**Comment by speedlorenzo12** [comment]
Inserted into the client that translates all settings (except plugin names and themes) in base alla lingua di discord, Maybe it can be a secondary purpose but useful in the future a usefull add to Revenge That lacked in  vendetta

**Comment by nexpid** [comment]
they're referring to this afaik, https://crowdin.com/project/nexpid-vendetta-plugins
I added translation support to some of my plugins, would be cool to see this in base Revenge

**Comment by riivx** [comment]
almost done, you can already work on translations here
https://crowdin.com/project/revenge-mod

the only thing that's left to do is fix some things and then I'll PR it

**Comment by speedlorenzo12** [comment]
When I can I will work on Italian

**Comment by speedlorenzo12** [comment]
When I can I will work on Italian

**Comment by XAlboX** [comment]
> When I can I will work on Italian 

Nuh uh, I will 🫂

**Comment by lunyaUwU** [comment]
I can work on german :3

**Comment by SodaWithoutSparkles** [comment]
> > When I can I will work on Italian 
> 
> Nuh uh, I will 🫂

Nah *we* will

*communism intensities*

**Comment by riivx** [comment]
if you want to translate a language that isn't in the list on crowdin just tell me and i'll add

**Comment by speedlorenzo12** [comment]
Another small idea, add the possibility of being able to insert either the discord language, or manually choose another language since it may happen that you don't understand something

**Comment by riivx** [comment]
idea is ok, explanation - just horror
> since it may happen that you don't understand something

at this point, lets add lang switcher to every app with translations 😨

**Comment by speedlorenzo12** [comment]
Ok let's go back to the original idea, it's better

**Comment by speedlorenzo12** [comment]
Ok let's go back to the original idea, it's better

**Comment by PalmDevs** [comment]
Moved this to Backlog for now, we'll have to think of a good way to do localization
