### ISSUE TITLE
[Bug] Discord server link not updated

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [revenge-mod/Revenge#14]
Link in Settings > General > Discord server is not updated

I'll fork and PR a fix soon.

**Comment by SodaWithoutSparkles** [comment]
Things to modify are probably at

https://github.com/revenge-mod/Revenge/blob/b6c3cd0f9a719b0fc9cbbc4ebd991592e2031693/src/lib/constants.ts#L3

https://github.com/revenge-mod/Revenge/blob/main/src/ui/quickInstall/forumPost.tsx

**Comment by SodaWithoutSparkles** [comment]
For now I won't modify the channel IDs and server IDs. These are mainly used when installing plugins. 

The reason is that it doesn't make sense for ReVenge to use the same proxy as vendetta. IF we were to introduce the same functionality, we would need to have our proxy thingy.

https://github.com/revenge-mod/Revenge/blob/b6c3cd0f9a719b0fc9cbbc4ebd991592e2031693/src/lib/constants.ts#L3-L5
https://github.com/revenge-mod/Revenge/blob/b6c3cd0f9a719b0fc9cbbc4ebd991592e2031693/src/ui/quickInstall/forumPost.tsx#L17-L26

**Comment by riivx** [comment]
even if Palm adds revenge proxy, vendetta will probably stay as legacy one. for now please don't change proxy-dependent constants
