### ISSUE TITLE
Error when following instructions 

### ISSUE THREAD

**Issue by Gamerboi520** [revenge-mod/Revenge#20]
![Screenshot_20240306_111608](https://github.com/revenge-mod/Revenge/assets/84089845/7c0c6a06-5d4f-43f9-ab74-31e844e8c92b)
![Screenshot_20240306_111547](https://github.com/revenge-mod/Revenge/assets/84089845/d8e920fd-e57b-416b-9821-8e2cbc5ba9a6)

**Comment by Gamerboi520** [comment]
![Screenshot_20240306_111718_File Viewer](https://github.com/revenge-mod/Revenge/assets/84089845/2910beb7-a433-4058-9b54-34f6a77f744d)
![Screenshot_20240306_111706_Vendetta Manager](https://github.com/revenge-mod/Revenge/assets/84089845/84eb164f-2ebf-4794-bebb-0c2d0c5acc5d)

**Comment by Gamerboi520** [comment]
Should have everything done right so im confused on what i did wrong 
![Screenshot_20240306_111831_Vendetta Manager](https://github.com/revenge-mod/Revenge/assets/84089845/f483df82-52b1-4a3c-98c6-0c95254268af)

**Comment by Gamerboi520** [comment]
Booted in safe mode
![Screenshot_20240306_112017](https://github.com/revenge-mod/Revenge/assets/84089845/028d3a3b-1ad9-40c5-9faf-0668010ff6f4)

**Comment by Gamerboi520** [comment]
Even says revenge so im not understanding what's wrong any help?

![Screenshot_20240306_112544](https://github.com/revenge-mod/Revenge/assets/84089845/6b027ca9-6c1e-4976-8c26-f66e8b859e48)

**Comment by Gamerboi520** [comment]
Well it's unconventional and strange but disabling all plugins in safe mode then re-enabling them in normal mode fixed it idk how but eh

**Comment by nexpid** [comment]
> Well it's unconventional and strange but disabling all plugins in safe mode then re-enabling them in normal mode fixed it idk how but eh

That's weird, I wonder why that worked!
![image](https://github.com/revenge-mod/Revenge/assets/60316309/77373d64-a9d6-4492-b72a-64a47f0d86df)
crazy...

**Comment by Gamerboi520** [comment]
Good eye it was the only plugin i didn't re-enable i since deleted it lol it's useless thanks 👍
