### ISSUE TITLE
Vendetta issue or Revenge?

### ISSUE THREAD

**Issue by MaiSan9999** [revenge-mod/Revenge#21]
so i noticed "shortcut" doesnt work on vendetta / revenge. discord stable work perfectly
"shortcut" don't know the exact term sorry
 
theres 2 recording one with vendetta the other one with revenge
https://github.com/revenge-mod/Revenge/assets/89659009/bdbe7fc3-ff2e-458f-8511-2de5b874c855

https://github.com/revenge-mod/Revenge/assets/89659009/c8bd47d9-c6d1-406e-a6cb-11c59d0378e0
is this fixxable with settings? cause nothing goes in my mind trying to get shortcut working i also tried disabling vendetta/revenge open as default setting
![image](https://github.com/revenge-mod/Revenge/assets/89659009/b9e5508f-8a50-4ba5-b014-64f8fe162fe3)

**Comment by MasterCraft6969** [comment]
That looks like an issue caused by your browser. What you are referring to is opening a link from an app (for example Youtube.com/watch?example to open in the YT app), in the app and not the browser, right?

**Comment by MaiSan9999** [comment]
> That looks like an issue caused by your browser. What you are referring to is opening a link from an app (for example Youtube.com/watch?example to open in the YT app), in the app and not the browser, right?

yep kinda? .
but it's really weird cause with yt links revenge has no issue opening in app of course same for discord "official".
i don't know in the video shown the shortcut start my chrome browser instead the app.

**Comment by riivx** [comment]
i think (because of the ui on the video) old version is the problem
