### ISSUE TITLE
Doesn't work on non-root A14 QPR2

### ISSUE THREAD

**Issue by riivx** [revenge-mod/Revenge#22]
we're receiving reports that Revenge doesn't work on Android 14 QPR2 because of LSPatch. if you have any issues, please report here!

**Comment by janisslsm** [comment]
It's because of https://github.com/LSPosed/LSPosed/issues/2869

**Comment by janisslsm** [comment]
Forgot to mention but it's been fixed in https://github.com/mywalkb/LSPosed_mod but you'd have to fork LSPatch and change the LSPosed submodule to point to that and rebuild.

**Comment by riivx** [comment]
i can assign it to you if you want

**Comment by janisslsm** [comment]
Fixed with https://github.com/vendetta-mod/VendettaManager/pull/77 though will have to wait for it to be merged, can use the [actions build](https://github.com/vendetta-mod/VendettaManager/actions/runs/8215048399) for now

**Comment by riivx** [comment]
will be fixed soon ([source](https://github.com/Aliucord/Aliucord/issues/427#issuecomment-1986926273))

**Comment by Ushie** [comment]
https://github.com/vendetta-mod/VendettaManager/pull/77 was merged
