### ISSUE TITLE
CloudSync plugins

### ISSUE THREAD

**Issue by 4NXIE7Y** [revenge-mod/Revenge#36]
Trying to import the Plugins used in Vendetta via CloudSync seems to bug Revenge...
![Screenshot_20240320_203837](https://github.com/revenge-mod/Revenge/assets/98228741/f6d6a694-8db6-454c-a9bc-adb520610eb4)

**Comment by riivx** [comment]
can you show the stack trace?

**Comment by 4NXIE7Y** [comment]
Fixed the issue by manually adding the CloudSync plugin via https://vendetta.nexpid.xyz/cloud-sync/
Initially installed the plugin by clicking a link from the Vendetta's server which for some reason caused the issue...
