### ISSUE TITLE
No icons

### ISSUE THREAD

**Issue by alexander-horne** [revenge-mod/Revenge#37]
Hi there !

I've just installed the latest version of Vendetta and I have Xposed too.
It seems that I've lost completely all icons related to Discord.

Cheers !
Alex
![Screenshot_20240320-174923](https://github.com/revenge-mod/Revenge/assets/55353662/aa718fb3-dd50-4ef5-bad5-5dbfc8de3a4b)
![Screenshot_20240320-174918](https://github.com/revenge-mod/Revenge/assets/55353662/69ae33ad-8f48-42e5-9244-9f574ea31a01)

**Comment by riivx** [comment]
it this is still relevant, can you show more info?
Revenge -> General -> Versions/Platform (please show both)
