### ISSUE TITLE
Stuck on loading icon (221.16 Stable)

### ISSUE THREAD

**Issue by LiamTheNinja5** [revenge-mod/Revenge#38]
I followed the install instructions in the readme but still have this issuse

**Comment by darbdarb** [comment]
Same here, just updated and no longer loading. When I try default, I get a crash report.

**Comment by riivx** [comment]
did you use a link to load revenge by any chance?
if yes, please use xposed module

**Comment by riivx** [comment]
you didn't answer the question

**Comment by darbdarb** [comment]
Change version: It's been pinned on this github

Changed it to 222013 and no more loading issue
