### ISSUE TITLE
What's up with the font?

### ISSUE THREAD

**Issue by a-usr** [revenge-mod/Revenge#40]
I just installed revenge because with the latest update vendetta would be stuck on a endless loading screen, and upon opening the app I noticed the font was... Off...
I'd send a screenshot but the GitHub app won't let me. Maybe someone changed the default font with the latest pr?

**Comment by a-usr** [comment]
Ah there we go

![Screenshot_20240324_214255.jpg](https://github.com/revenge-mod/Revenge/assets/81042605/d81f51d6-cf1d-4c86-9316-09af8fa6bb45)

**Comment by riivx** [comment]
what theme are you using? if that's possible, please send the url of it

**Comment by a-usr** [comment]
Ah, I forgot about the theme.
https://raw.githubusercontent.com/VodkaXMartini/VendettaTheme/main/Vision.json


Turning off the theme fixed the font. However on vendetta this theme didn't change the font for some reason.

**Comment by riivx** [comment]
because vendetta doesn't have custom fonts support, we added it

**Comment by a-usr** [comment]
I investigated real quick, and last week the creator pushed a commit wich made the theme change the font. I'm guessing vendetta didn't support that and just ignored the keys for that? anyhow I'm closing this. Thanks for pointing me in the right direction!
