### ISSUE TITLE
Suggestion: Maybe a name change?

### ISSUE THREAD

**Issue by TradStick49** [revenge-mod/revenge#44]
You can disagree with me if you want, but I've been thinking. There's been Vendetta, Enmity... and then Revenge. 

Sure they all mean the same, but "Revenge" feels blander than the others. There's other synonyms which mean roughly the same like Rancor, Acrimony, Animosity, etc

I just feels like one of those would be better.
Again you can disagree and I respect that, it's just a thought I just had.

**Comment by oSumAtrIX** [comment]
Branding is a topic we are currently talking about. Some unfinal changes are being discussed

**Comment by catnipjson** [comment]
call it meowcord real

**Comment by catnipjson** [comment]
i agree
