### ISSUE TITLE
Chat bubbles for messages sent in chat

### ISSUE THREAD

**Issue by Moodzz1** [revenge-mod/revenge#46]
So the Enmity discord mod has a fork known as [rosiecord](https://github.com/acquitelol/rosiecord). Rosiecord has an optional tweak known as [flowercord](https://github.com/acquitelol/rosiecord?tab=readme-ov-file#what-is-flowercord) which adds chat bubbles and square pfp's to the chat area. No one at Vendetta did this, likewise with bunny. Considering how Revenge is making a "comeback" and has more Devs than last time (I'm guessing), I was gonna ask could someone make this for Revenge? I've been told the chat area is native so it has to be done to the tweak/xposed module but regardless I'd love it if someone could do this. Myself and other people have wanted this since Vendetta 💔 and iOS/Enmity users have been able to enjoy these for basically 666 years so us Android users miss out.

I doubt anyone will do this but in the off chance someone does, the request is here

Here is the [standalone tweak](https://github.com/khcrysalis/flowercord) for flowercord

**Comment by Cristiandis** [comment]
hey, i just tested this, flowercord does work with revenge, atleast on ios, if you want i can add a build option for it on my custom revenge builds :3

**Comment by Moodzz1** [comment]
Well I'm not an iOS user so uh idk. Ig it would be nice for the iOS users ig tho?

**Comment by oSumAtrIX** [comment]
Plugin requests don't go here. Currently there is no place to request them.

**Comment by Moodzz1** [comment]
1. This was not a plugin request...
2. If you had read what I said, I said I have been told this must be implemented within the tweak/xposed module itself and not a plugin 
Reading comprehension be non existent these days

**Comment by oSumAtrIX** [comment]
Neither is this related to a tweak/xposed nor is this the tweak/xposed repository. So yes, reading comprehension be non existent these days.

**Comment by catnipjson** [comment]
???

**Comment by Moodzz1** [comment]
It was related to the mod and I wasn't 100% sure to whether I was right with that. I'm not opening an issue on 2 different repo's with the exact same message

**Comment by catnipjson** [comment]
yea i can confirm this was not a plugin request
