### ISSUE TITLE
bug: some servers don't load correctly on first app open

### ISSUE THREAD

**Issue by qwyop** [revenge-mod/Revenge#56]
only happens on first opening of the app (not open in the background). seems to be common with servers that require you to react to a message to unlock the other channels, but some that don't need to also have this issue. toggling safe mode on doesn't change this behavior. video recording shows what it looks like and how putting it in the background and refocusing fixes it.

https://github.com/user-attachments/assets/dde0070a-ac9b-48b5-9b4f-9e8f1bba2eca

![Screenshot of the Revenge Settings→About→Info page which shows information about its current installed version along with Platform (device) it's installed on](https://github.com/user-attachments/assets/42505642-9383-4d75-95f9-f42f3bc5396b)
* Revenge c0d8bc9-main (v1.5.2) on Discord 254.27 (254027)
  * installed with Revenge Manager v1.0.0
* Device: Samsung Galaxy Note 8
* OS: Android 9 (OneUI 1.0)

**Comment by 0withoutface0** [comment]
Can verify that it happens. I'm on rootless version. 

Only shows the verify channel even tho I already verified on another version of discord. Restarting or refocusing the app fixes the problem.

![Screenshot_2024-11-18-10-25-36-142_app.revenge.jpg](https://github.com/user-attachments/assets/1dc52ae3-8035-4e67-b188-013b756b24b2)

**Comment by xuara** [comment]
This has been happening with me as well. Restarting/re-focusing hasn't ever worked, but opening the verify channel as mentioned by previous report does fix it.

![Screenshot_20241118_124624.jpg](https://github.com/user-attachments/assets/93195aa5-9d11-45e2-9e0e-7abe64a6dc39)

![Screenshot_20241118_124633.jpg](https://github.com/user-attachments/assets/ae3efdf5-ec00-44e7-8e8f-62596e8a9d72)

**Comment by Andre601** [comment]
I believe this to be a more general discord issue, as I myself encounter this with Bunny itself and usually in servers that have the "Channel & Roles" thing setup where you obtain roles and channel access via selecting answers.

Was thinking of switching to Revenge, but given this issue also seems to be present here will I probs wait for the time being and hope this can be fixed somehow.
