### ISSUE TITLE
non rooted option

### ISSUE THREAD

**Issue by keatit71** [revenge-mod/Revenge#6]
How do I install this without root?

**Comment by naloder** [comment]
check the readme

**Comment by keatit71** [comment]
Oh I thought maybe I needed something different but it worked thanks. Will there be a auto updating version or will i need to re-download it everytime there's an update?

**Comment by PalmDevs** [comment]
> Oh I thought maybe I needed something different but it worked thanks. Will there be a auto updating version or will i need to re-download it everytime there's an update?

Discord update, yes. Revenge update, no.
