### ISSUE TITLE
make a discord (real)

### ISSUE THREAD

**Issue by womanburner** [revenge-mod/Revenge#8]
real

**Comment by PalmDevs** [comment]
?

**Comment by womanburner** [comment]
make a discord server like (v)endetta

**Comment by kasmisdre** [comment]
are you ok mentally

**Comment by magmaus3** [comment]
hint: [look here](https://github.com/revenge-mod)

**Comment by womanburner** [comment]
> hint: [look here](https://github.com/revenge-mod)

bro when he discovers i said make a discord (there wasnt a discord) and then there is a discord shocking turn of events right

**Comment by PalmDevs** [comment]
> > hint: [look here](https://github.com/revenge-mod)
> 
> bro when he discovers i said make a discord (there wasnt a discord) and then there is a discord shocking turn of events right

hint: look below
![Screenshot disproving your argument](https://github.com/revenge-mod/Revenge/assets/67689562/eff49983-cebd-4052-b8e8-87c7bf99fe75)

**Comment by Ushie** [comment]
There was no invite in the readme, hence the issue, not sure why the aggression

**Comment by PalmDevs** [comment]
> There was no invite in the readme at the time, hence the issue, not sure why the aggression

The invite has been added to the organization "links" which is displayed in the banner since the server has existed. Although it may not be obvious, it can clearly be seen.

![Screenshot](https://github.com/revenge-mod/Revenge/assets/67689562/a8b0d97e-4a7e-4324-830b-953d9b78b5e2)
